name: Dispatch env inputs smoke

on:
  workflow_dispatch:
    inputs:
      foo:
        required: true
        default: "bar"

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      FOO: ${{ inputs.foo }}
    steps:
      - run: echo "FOO=$FOO"
