name: Release lite

on:
  workflow_dispatch:

jobs:
  lite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Echo
        run: |
          echo "ok"
          date -u
